services:
  nginx:
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - "8080:80"
    networks:
      - symfony

  php:
    build: 
      context: .
      dockerfile: config/php/Dockerfile
    environment:
      - APP_ENV=dev
    volumes:
      - ./symfony/:/var/www/symfony/
    command: >
      sh -c "php-fpm &
      php /var/www/symfony/bin/console messenger:consume async_priority_high async -vv"
    networks:
      - symfony
    depends_on:
      - postgres

  postgres:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - symfony
      
networks:
  symfony: